### ISSUE TITLE
ModuleNotFoundError: No module named 'wcmatch'

### ISSUE THREAD

**Issue by brian6932** [sublimelsp/LSP-gopls#79]
LSP: 2.0.0
gopls: 1.16.0
ST: Build 4173

Getting the following stack, gopls doesn't start:
```
reloading plugin LSP-gopls.boot
Traceback (most recent call last):
  File "~\scoop\apps\sublime-text\current\Lib\python38\sublime_plugin.py", line 325, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.8/importlib/__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 868, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP-gopls.sublime-package\boot.py", line 12, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP-gopls.sublime-package\plugin/__init__.py", line 2, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP-gopls.sublime-package\plugin/commands.py", line 9, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP-gopls.sublime-package\plugin/vulnerabilities.py", line 5, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP-gopls.sublime-package\plugin/utils.py", line 8, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/__init__.py", line 12, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/registry.py", line 4, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/sessions.py", line 3, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/diagnostics_storage.py", line 4, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/views.py", line 39, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/settings.py", line 3, in <module>
  File "~\scoop\persist\sublime-text\Data\Installed Packages\LSP.sublime-package\plugin/core/types.py", line 9, in <module>
ModuleNotFoundError: No module named 'wcmatch'
```

**Comment by brian6932** [comment]
Ok this doesn't seem like a gopls issue, sorry, should be reported to LSP itself I think.
