### ISSUE TITLE
Can't install gopls

### ISSUE THREAD

**Issue by jingyuexing** [sublimelsp/LSP-gopls#9]
![image](https://user-images.githubusercontent.com/19589872/138940197-5c0122aa-f673-46d2-a4c5-a27883759055.png)

**Comment by ofen** [comment]
I have different error on linux machine (20.04.2 LTS (Focal Fossa) go1.13.8)
```
Unable to start subprocess for gopls
Traceback (most recent call last):
  File "/home/user/.config/sublime-text-3/Installed Packages/LSP.sublime-package/plugin/core/windows.py", line 333, in start_async
    plugin_class.install_or_update()
  File "/home/user/.config/sublime-text-3/Installed Packages/LSP-gopls.sublime-package/plugin.py", line 77, in install_or_update
    'go installation error', stderr, 'returncode', process.returncode)
ValueError: ('go installation error', b"can't load package: package golang.org/x/tools/gopls@v0.7.3: can only use path@version syntax with 'go get'\n", 'returncode', 1)
```
go env
```
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOENV="/home/user/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/user/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/lib/go-1.13"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/go-1.13/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/user/test/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build176085849=/tmp/go-build -gno-record-gcc-switches"
```

**Comment by TheSecEng** [comment]
Hey thanks for the info! We are working to resolve this. Essentially we are supporting gopls 1.16+ right now. So we need to work on supporting those below 1.16. This is actively being worked on.

**Comment by TheSecEng** [comment]
fix: #10

**Comment by jingyuexing** [comment]
> fix: #10

Oh yeah! 🎉

**Comment by jingyuexing** [comment]
# Troubleshooting: gopls
## Version
 - LSP: 1.13.0
 - Sublime Text: 4100
## Server Test Run
 - exit code: -1
 - output
```
('go installation error', b'go: creating work dir: mkdir C:\\WINDOWS\\go-build169076251: Access is denied.\n', 'returncode', 1)
```
## Server Configuration
 - command
```json
[
  "${storage_path}/LSP-gopls/gopls"
]
```
 - shell command
```sh

```
 - selector
```
source.go | source.gomod
```
 - priority_selector
```
source.go | source.gomod
```
 - init_options
```json
{}
```
 - settings
```json
{
  "gopls": {
    "allowImplicitNetworkAccess": false, 
    "allowModfileModifications": false, 
    "analyses": {}, 
    "annotations": {}, 
    "buildFlags": [], 
    "codelenses": {}, 
    "completionBudget": "100ms", 
    "diagnosticsDelay": "250ms", 
    "directoryFilters": [], 
    "env": {}, 
    "expandWorkspaceToModule": true, 
    "experimentalPackageCacheKey": true, 
    "experimentalPostfixCompletions": true, 
    "experimentalTemplateSupport": false, 
    "experimentalWorkspaceModule": false, 
    "gofumpt": false, 
    "hoverKind": "FullDocumentation", 
    "importShortcut": "Both", 
    "linkTarget": "pkg.go.dev", 
    "linksInHover": true, 
    "local": "", 
    "matcher": "Fuzzy", 
    "memoryMode": "Normal", 
    "semanticTokens": false, 
    "staticcheck": false, 
    "symbolMatcher": "Fuzzy", 
    "symbolStyle": "Dynamic", 
    "usePlaceholders": false, 
    "verboseOutput": false
  }
}
```
 - env
```json
{}
```

## Active view
 - File name
```
I:\Code\go\Study_GO\Frist.go
```
 - Settings
```json
{
  "auto_complete_selector": "meta.tag, source - comment - string.quoted.double.block - string.quoted.single.block - string.unquoted.heredoc", 
  "lsp_active": true, 
  "syntax": "Packages/Go/Go.sublime-syntax"
}
```
 - base scope
```
source.go
```

## Project / Workspace
 - folders
```json
[
  "I:\\Code\\go\\Study_GO"
]
```
 - is project: False

## LSP configuration

```json
{
  "clients": {
    "D": {
      "command": [
        "dls"
      ], 
      "enabled": true, 
      "selector": "source.d"
    }, 
    "clangd": {
      "enabled": true
    }, 
    "cmake": {
      "command": [
        "cmake-language-server"
      ], 
      "enabled": true, 
      "selector": "CMakeLists.txt| source.cmake"
    }, 
    "gopls": {
      "command": [
        "${storage_path}/LSP-gopls/bin/gopls"
      ], 
      "enabled": true
    }, 
    "groovy-language-server": {
      "command": [
        "groovy-language-server-all"
      ], 
      "enabled": true, 
      "selector": "source.groovy"
    }, 
    "kotlinls": {
      "command": [
        "kotlin-language-server"
      ], 
      "enabled": true, 
      "selector": "source.Kotlin", 
      "settings": {
        "kotlin": {}
      }
    }, 
    "mspyls": {
      "command": [
        "dotnet.exe", 
        "exec", 
        "C:\\Language-server\\Microsoft.Python.LanguageServer.dll"
      ], 
      "initializationOptions": {
        "interpreter": {
          "properties": {
            "UseDefaultDatabase": true, 
            "Version": "3.7"
          }
        }
      }, 
      "selector": "source.python"
    }, 
    "ocaml": {
      "command": [
        "I:/Programming/sublime_text_4100/Data/Package Storage/Ocaml/reason-language-server.exe", 
        "--stdio"
      ], 
      "enabled": true, 
      "selector": "source.reason | source.ocaml"
    }, 
    "pyls": {
      "command": [
        "pyls"
      ], 
      "enabled": true, 
      "selector": "source.python", 
      "settings": {
        "pyls.configurationSources": [
          "flake8"
        ]
      }
    }, 
    "ruby": {
      "enabled": true, 
      "selector": "source.rb | source.ruby| text.html.rb | text.html.ruby"
    }, 
    "zig": {
      "command": [
        "E:\\Programming\\Zig\\zls\\zls.exe"
      ], 
      "enabled": true, 
      "scopes": "source.zig"
    }
  }, 
  "log_debug": true, 
  "log_server": [
    "panel"
  ]
}

**Comment by TheSecEng** [comment]
Is this using the latest release? Something seems funky. You have 
```
    "gopls": {
      "command": [
        "${storage_path}/LSP-gopls/bin/gopls"
      ], 
      "enabled": true
    },
```

And 

```
[
  "${storage_path}/LSP-gopls/gopls"
]
```

Which seems you have multiple configurations. 

What is the output of `go env`

**Comment by rchl** [comment]
You are not supposed to define your own gopls configuration when using an LSP-* package. Just remove the one from the global LSP settings.
